2020-01-04 00:00:38 [scrapy.pipelines.files] WARNING: File (code: 404): Error downloading file from <GET https://restp.dongqiniqin.com//images/comic/216/430480/https://manhua.qpic.cn/manhua_detail/0/12_11_12_4ef7606fe12cfd89870445231b8e0bb4_28125.jpg/0> referred in <None>
2020-01-04 00:03:15 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557911860PO7f_w7XfpG0FRqM.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557911860PO7f_w7XfpG0FRqM.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557911912BU37PmiU77VHoD1o.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557911912BU37PmiU77VHoD1o.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905458-uGv3TvWkm31cMNM.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905458-uGv3TvWkm31cMNM.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905458TFn_r0WPrSSMoNem.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905458TFn_r0WPrSSMoNem.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905459Wdf94-2BSE8BoT_A.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905459Wdf94-2BSE8BoT_A.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905460uz8rLR1NoGX_PgJD.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905460uz8rLR1NoGX_PgJD.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905467x39Zi5CFygPgrHLt.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905467x39Zi5CFygPgrHLt.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905476--aUDmobpclJTWwe.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905476--aUDmobpclJTWwe.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/15579054869zC1xfAQF3LrXNSJ.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/15579054869zC1xfAQF3LrXNSJ.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:16 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905496W4OFFN9r5rRTgL8P.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905496W4OFFN9r5rRTgL8P.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905505IZyKZUBB04-65Ur2.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905505IZyKZUBB04-65Ur2.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905516w7IEGxKBED_UuGXy.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905516w7IEGxKBED_UuGXy.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/15579055287MDd0TERBWfmc3f_.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/15579055287MDd0TERBWfmc3f_.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905541ihbcyydp9fb6ms_4.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905541ihbcyydp9fb6ms_4.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905556LK75lCDtvRc_i2I1.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905556LK75lCDtvRc_i2I1.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905570Bhgq-aHVmdA1JRdH.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905570Bhgq-aHVmdA1JRdH.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905584vm84eZaXFecqfP-F.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905584vm84eZaXFecqfP-F.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:17 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905599g5vRa3tdq9EnhDAy.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905599g5vRa3tdq9EnhDAy.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905618-u_ovZBLhjCCFqI3.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905618-u_ovZBLhjCCFqI3.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905632ORoXfNqyqzePCKrV.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905632ORoXfNqyqzePCKrV.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905644bxIkXqhncANqmTx-.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905644bxIkXqhncANqmTx-.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905656J1hQXk-WLHEbdAz5.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905656J1hQXk-WLHEbdAz5.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905679I7Yogpugdpl4oDsR.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905679I7Yogpugdpl4oDsR.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905668oNqeyUr4ti8exfF3.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905668oNqeyUr4ti8exfF3.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905694coX2xlLlChgDX3lO.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905694coX2xlLlChgDX3lO.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:18 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905707UsXmU-5AhirNKxIn.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905707UsXmU-5AhirNKxIn.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905722ae30RlyjhECDN_fp.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905722ae30RlyjhECDN_fp.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905735aMGaW5R-NLK9O-e1.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905735aMGaW5R-NLK9O-e1.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905748dXLwBsZ3ghUPgVju.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905748dXLwBsZ3ghUPgVju.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905765KRL11CgnkMJhAjr0.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905765KRL11CgnkMJhAjr0.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905777YUOyThOIp977FXBa.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905777YUOyThOIp977FXBa.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905789Q87nuMQxm3sq39fM.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905789Q87nuMQxm3sq39fM.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905802TRwV_Nr9f4OsvjvV.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905802TRwV_Nr9f4OsvjvV.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:19 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905814pIYoqHPNu7kRGp_T.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905814pIYoqHPNu7kRGp_T.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905833Fcxl1iO14hulDB1x.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905833Fcxl1iO14hulDB1x.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905845FXhUcCLZsaBoWykh.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905845FXhUcCLZsaBoWykh.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905856CrQ4gROeiief3yUH.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905856CrQ4gROeiief3yUH.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905870EsO-xiovuNsT7F8T.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905870EsO-xiovuNsT7F8T.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905882clyeAtGYT-szYlCD.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905882clyeAtGYT-szYlCD.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905893kbXD-6gAYynuMNx4.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905893kbXD-6gAYynuMNx4.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905905p9c_lZEdiTYdCIok.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905905p9c_lZEdiTYdCIok.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:20 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905919QdssZ8fqBlG3kSJ2.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905919QdssZ8fqBlG3kSJ2.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905933QKiIsmcAKahq7DRr.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905933QKiIsmcAKahq7DRr.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905945k7vMRUbGy8BspPm2.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905945k7vMRUbGy8BspPm2.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905957yIGqHlC9uyp8Gsj-.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905957yIGqHlC9uyp8Gsj-.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905971mFSj4k52WhOWPHYn.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905971mFSj4k52WhOWPHYn.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557905987ettLUUyb_YyBp_eE.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557905987ettLUUyb_YyBp_eE.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557906001_82hZYDu-oS8oN7-.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557906001_82hZYDu-oS8oN7-.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557906082ujTr-V-iI9okzKKN.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557906082ujTr-V-iI9okzKKN.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557906094moeuWaigEmetqEGC.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557906094moeuWaigEmetqEGC.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:21 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/1557906123jTTbdxoH_QNorqNZ.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/1557906123jTTbdxoH_QNorqNZ.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 00:03:22 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://restp.dongqiniqin.com//images/comic/193/384886/15579061575b_qS8CXkn5D3D1r.jpg> referred in <None>
Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "C:\Program Files\python3.6.8\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://restp.dongqiniqin.com//images/comic/193/384886/15579061575b_qS8CXkn5D3D1r.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 434, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\images.py", line 118, in image_downloaded
    headers={'Content-Type': 'image/jpeg'})
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 54, in persist_file
    self._mkdir(os.path.dirname(absolute_path), info)
  File "C:\Program Files\python3.6.8\lib\site-packages\scrapy\pipelines\files.py", line 78, in _mkdir
    os.makedirs(dirname)
  File "C:\Program Files\python3.6.8\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:/home/tarena/manhua/特别番外?三十六贼之魏淑芬'
2020-01-04 09:11:39 [twisted] CRITICAL: Unhandled error in Deferred:
2020-01-04 09:11:39 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.6/dist-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/misc.py", line 140, in create_instance
    return objcls.from_crawler(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/pipelines/media.py", line 68, in from_crawler
    pipe = cls.from_settings(crawler.settings)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/pipelines/images.py", line 99, in from_settings
    return cls(store_uri, settings=settings)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/pipelines/images.py", line 52, in __init__
    download_func=download_func)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/pipelines/files.py", line 289, in __init__
    self.store = self._get_store(store_uri)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/pipelines/files.py", line 332, in _get_store
    store_cls = self.STORE_SCHEMES[scheme]
KeyError: 'f'
2020-01-04 09:51:08 [scrapy.pipelines.files] WARNING: File (code: 404): Error downloading file from <GET https://restp.dongqiniqin.com//images/comic/216/430480/https://manhua.qpic.cn/manhua_detail/0/12_11_12_4ef7606fe12cfd89870445231b8e0bb4_28125.jpg/0> referred in <None>
2020-01-04 10:05:18 [scrapy.pipelines.files] WARNING: File (code: 404): Error downloading file from <GET https://restp.dongqiniqin.com//images/comic/216/430480/https://manhua.qpic.cn/manhua_detail/0/12_11_12_4ef7606fe12cfd89870445231b8e0bb4_28125.jpg/0> referred in <None>
